@Host=http://localhost:5031

POST {{Host}}/auth/register
Content-Type: application/json

{
    "firstName":"Franklin",
    "lastName": "Wagbara",
    "email":"wagbara@yahoo.com",
    "password":"password"
}

